/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d6da2e0c7b8cc07050daed4af7fb7e6e)
interface __BaseEnv_Env {
	DB: D1Database;
	ASSETS: Fetcher;
	RESEND_API_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESEND_API_KEY">> {}
}
