services:
  floci:
    image: floci/floci:latest
    container_name: floci
    ports:
      - "4566:4566"
    volumes:
      - floci-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FLOCI_STORAGE_MODE: persistent
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
    restart: unless-stopped

volumes:
  floci-data: